# Generated by Django 4.1.7 on 2023-03-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='care_request',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='care_request',
            old_name='contractor_id',
            new_name='contractor',
        ),
    ]
