# Generated by Django 4.1.7 on 2023-03-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255)),
                ('care_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_requests.care_request')),
            ],
        ),
    ]
