# Generated by Django 4.1.7 on 2023-03-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='care_request_id',
            new_name='user_request',
        ),
    ]
