# Generated by Django 4.1.7 on 2023-03-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_care_request_id_note_user_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_request',
            new_name='care_request',
        ),
    ]
